routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/


// Product

Route::group([
    'prefix' => 'product',
    'as' => 'product.',
    'namespace' => 'Product',
    ], function () {

    Route::get('',                 ['as' => 'index',  'uses' => 'ProductController@index']);

    Route::get('create',           ['as' => 'create', 'uses' => 'ProductController@create']);


    Route::group([
        'prefix' => '{productId}',
        ], function () {

        Route::get('',             ['as' => 'show',  'uses' => 'ProductController@show']);

        Route::post('save',        ['as' => 'save',   'uses' => 'ProductController@save']);

        Route::get('edit',         ['as' => 'edit',   'uses' => 'ProductController@edit']);

        Route::any('update',       ['as' => 'update', 'uses' => 'ProductController@update']);

        Route::any('delete',       ['as' => 'delete', 'uses' => 'ProductController@delete']);


        // ProductImage

        Route::group([
            'prefix' => 'product__image',
            'as' => 'product__image.',
            ], function () {

            Route::get('',             ['as' => 'index',  'uses' => 'ProductImageController@index']);

            Route::get('create',       ['as' => 'create', 'uses' => 'ProductImageController@create']);
            
            Route::post('save',        ['as' => 'save',   'uses' => 'ProductImageController@save']);

            Route::get('edit/{id}',    ['as' => 'edit',   'uses' => 'ProductImageController@edit']);

            Route::any('update/{id}',  ['as' => 'update', 'uses' => 'ProductImageController@update']);

            Route::any('delete/{productImageId}',  ['as' => 'delete', 'uses' => 'ProductImageController@delete']);

        });

    });

});


// User

Route::group([
    'prefix' => 'user',
    'as' => 'user.',
    'namespace' => 'User',
    ], function () {

    Route::get('',         ['as' => 'index',  'uses' => 'UserController@index']);

    Route::get('edit/{id}',    ['as' => 'edit',   'uses' => 'UserController@edit']);
    Route::any('update/{id}',  ['as' => 'update', 'uses' => 'UserController@update']);

    Route::any('delete/{id}',  ['as' => 'delete', 'uses' => 'UserController@delete']);


    Route::group([
        'prefix' => 'cart',
        'as' => 'cart.'
        ], function () {

        Route::get('',          ['as' => 'index',
                                'uses' => 'UserProductController@index']);

        Route::get('create/{productId}',    ['as' => 'create',
                                'uses' => 'UserProductController@create']);

        Route::any('update/{userProductId}',['as' => 'update',
                                'uses' => 'UserProductController@update']);

        Route::any('delete/{userProductId}',  ['as' => 'delete',
                                   'uses' => 'UserProductController@delete']);

    });

});


// Order

Route::group([
    'prefix' => 'order',
    'as' => 'order.',
    'namespace' => 'Order',
    ], function () {

    Route::get('',             ['as' => 'index',  'uses' => 'OrderController@index']);

    Route::get('create',       ['as' => 'create', 'uses' => 'OrderController@create']);
    Route::post('save/{orderId}',        ['as' => 'save',   'uses' => 'OrderController@save']);

    Route::any('delete/{id}',  ['as' => 'delete', 'uses' => 'OrderController@delete']);


    Route::group([
        'prefix' => 'order__product',
        'as' => 'order__product.',
        'namespace' => 'Order',
        ], function () {

        Route::get('create',       ['as' => 'create', 'uses' => 'OrderProductController@create']);

        Route::any('delete/{id}',  ['as' => 'delete', 'uses' => 'OrderProductController@delete']);

    });
});


// Category

Route::group([
    'prefix' => 'category',
    'as' => 'category.',
    'namespace' => 'Category',
    ], function () {

    Route::get('',             ['as' => 'index',  'uses' => 'CategoryController@index']);

    Route::get('create',       ['as' => 'create', 'uses' => 'CategoryController@create']);
    Route::post('save',        ['as' => 'save',   'uses' => 'CategoryController@save']);

    Route::any('delete/{id}',  ['as' => 'delete', 'uses' => 'CategoryController@delete']);

});



// Home

Route::get('/', function(){
    return 'Laravel 5.3' . '<br><a href="/product">Продукты</a>';
});



    // Authentication Routes...
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout');

    // Registration Routes...
    Route::get('register', 'Auth\RegisterController@showRegistrationForm');
    Route::post('register', 'Auth\RegisterController@register');

    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');



    // Admin
    Route::get('admin', ['middleware' => 'admin', 'as' => 'admin', function() {

        return view('face.admin');

    }]);

app/Http/Controllers/Admin/Order/OrderController.php
<?php
namespace App\Http\Controllers\Admin\Order;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Model\Order\Order;
use Illuminate\Http\Request;

class OrderController extends Controller {

    public function index()
    {
        $order = Order::orderBy('id', 'desc')->paginate(10);

        return view('admin.order.order.index', [
            'order' => $order
        ]);
    }

    public function create()
    {
        return view('admin.order.order.create');
    }

    public function save(Request $request)
    {
        $order = new Order($request->all());

        $order->save();

        return redirect()->route('order.index');
    }

    public function edit($id)
    {
        $order = Order::find($id);

        return view('admin.order.order.edit', [
            'order' => $order
        ]);
    }

    public function update(Request $request, $id)
    {
        $order = Order::find($id);

        $order->update($request->all());

        return redirect()->route('order.index');
    }

    public function delete($id)
    {
        $order = Order::where('id', '=', $id);
        $order->delete();

        return redirect()->back();
    }
}

app/Http/Controllers/Admin/Order/OrderProductController.php
<?php
namespace App\Http\Controllers\Admin\Order;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Model\Order\OrderProduct;
use Illuminate\Http\Request;

class OrderProductController extends Controller {

    public function index()
    {
        $orderProduct = OrderProduct::orderBy('id', 'desc')->paginate(10);

        return view('admin.order.order__product.index', [
            'orderProduct' => $orderProduct
        ]);
    }

    public function create()
    {
        return view('admin.order.order__product.create');
    }

    public function save(Request $request)
    {
        $orderProduct = new OrderProduct($request->all());

        $orderProduct->save();

        return redirect()->route('orderProduct.index');
    }

    public function edit($id)
    {
        $orderProduct = OrderProduct::find($id);

        return view('admin.order.order__product.edit', [
            'orderProduct' => $orderProduct
        ]);
    }

    public function update(Request $request, $id)
    {
        $orderProduct = OrderProduct::find($id);

        $orderProduct->update($request->all());

        return redirect()->route('orderProduct.index');
    }

    public function delete($id)
    {
        $orderProduct = OrderProduct::where('id', '=', $id);
        $orderProduct->delete();

        return redirect()->back();
    }
}

app/Http/Controllers/Order/OrderController.php
<?php
namespace App\Http\Controllers\Order;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Model\Order\Order;
use App\Model\Order\OrderProduct;
use App\Model\User\UserProduct;
use App\Model\User\User;
use Illuminate\Http\Request;

class OrderController extends Controller {

    public function index()
    {
        $order = Order::orderBy('id', 'desc')->paginate(10);

        return view('face.order.index', [
            'order' => $order
        ]);
    }

    public function create(Request $request)
    {
        $order = new Order();

        $order->user_id = $request->user()->id;

        $order->save();

        $userProductList = UserProduct::where('user_id', '=', $order->user_id)->get();

        foreach ($userProductList as $userProduct)
        {
            $orderProduct = new OrderProduct();

            $orderProduct->product_id = $userProduct->product_id;

            $orderProduct->order_id = $order->id;

            $orderProduct->save();
        }

        $orderProductList = OrderProduct::where('order_id', '=', $order->id)
            ->get();


        return view('face.order.edit', [
            'orderProductList' => $orderProductList,
            'order' => $order
            ]);
    }

    public function save(Request $request, $orderId)
    {
        $order = Order::find($orderId);

        $order->amount = $request->amount;

        $order->total = $request->total;

        $userProduct = UserProduct::where('user_id', '=', $request->user()->id);

        $userProduct->delete();

        $order->save();

        return redirect()->route('order.index');
    }

    public function edit($id)
    {
        $order = Order::find($id);

        return view('face.order.edit', [
            'order' => $order
        ]);
    }

    public function update(Request $request, $id)
    {
        $order = Order::find($id);

        $order->update($request->all());

        return redirect()->route('order.index');
    }

    public function delete($id)
    {
        $order = Order::where('id', '=', $id);
        $order->delete();

        return redirect()->back();
    }
}

app/Http/Controllers/Order/OrderProductController.php
<?php
namespace App\Http\Controllers\Admin\Order;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Model\Order\OrderProduct;
use Illuminate\Http\Request;

class OrderProductController extends Controller {

    public function index()
    {
        $orderProduct = OrderProduct::orderBy('id', 'desc')->paginate(10);

        return view('admin.order.order__product.index', [
            'orderProduct' => $orderProduct
        ]);
    }

    public function create()
    {
        return view('admin.order.order__product.create');
    }

    public function save(Request $request)
    {
        $orderProduct = new OrderProduct($request->all());

        $orderProduct->save();

        return redirect()->route('orderProduct.index');
    }

    public function edit($id)
    {
        $orderProduct = OrderProduct::find($id);

        return view('admin.order.order__product.edit', [
            'orderProduct' => $orderProduct
        ]);
    }

    public function update(Request $request, $id)
    {
        $orderProduct = OrderProduct::find($id);

        $orderProduct->update($request->all());

        return redirect()->route('orderProduct.index');
    }

    public function delete($id)
    {
        $orderProduct = OrderProduct::where('id', '=', $id);
        $orderProduct->delete();

        return redirect()->back();
    }
}

resources/views/face/order/edit.blade.php
@extends('layouts.master')


@section('content')
<div class="container">

    <div class="row">

        <div class="col-md-8 col-md-offset-2">

            <div class="panel panel-default">

                <div class="panel-heading">

                    <form action="{{ route('order.save', $order->id) }}" method="post">

                        <input type="hidden" name="_token" value="{{ csrf_token() }}">

                        <div class="panel-heading">
                        	<h3 class="text">Оформление заказа</h3>
                        </div>


                        <table class="table">

                            <tr>

                                <td>id</td>

                                <td>Название</td>

                                <td>Цена</td>

                                <td>Изображение</td>

                                <td>В наличие</td>

                                <td>Количество</td>

                            </tr>

                            @foreach ($orderProductList as $orderProduct)

                            <tr>

                                <td>{{ $orderProduct->product->id }}</td>

                                <td>{{ $orderProduct->product->name }}</td>

                                <td>{{ $price = $orderProduct->product->price }}</td>

                                <td>

                                @if ($orderProduct->product->image()->get()->count())

                                	@foreach ($orderProduct->product->image()->take(1)->get() as $orderProductImage)

                                		<img src="{{ $orderProductImage->src('100x100') }}">

                                	@endforeach

                                @else

                                	Нет изображения

                                @endif                        

                                </td>

                                <td>
                                    {{ $orderProduct->product->availability >= 1 ? 'Да' : 'Нет' }}
                                </td>

                                <td>
                                    @php
                                        $quantity = $orderProduct->product
                                                    ->user_product()->get();
                                    @endphp

                                        {{ $quantity = $quantity[0]->quantity }}
                                </td>

                            </tr>

                            @php 
                            	$total[] = $price * $quantity;
                            	$quantityAll[] = $quantity;
                            @endphp

                            @endforeach

                        </table>

                        <hr>
                        <label for="quantityAll">Количество продуктов заказа: {{ $amount = array_sum($quantityAll) }}</label>

                        <input type="hidden" name="amount" value="{{ $amount }}">
                        
                        <br>
                        <label for="total">Сумма заказа: {{ $total = array_sum($total) }}</label>

                        <input type="hidden" name="total" value="{{ $total }}">      

                        <hr>


                        Город: 
                        {{ Auth::user()->city }}
                        <br>
                        Адрес: 
                        {{ Auth::user()->address }}

                        <hr>
                        <input type="submit" class="btn btn-primary" value="Подтвердить заказ">

                    </form>

                </div>

            </div>

        </div>

    </div>

</div>

@endsection

resources/views/face/order/index.blade.php
@extends('layouts.master')


@section('content')
<div class="container">

    <div class="row">

        <div class="col-md-8 col-md-offset-2">

            <div class="panel panel-default">

                <div class="panel-heading">

                    <div class="panel-heading">
                    	<h3 class="text">Ваши заказы</h3>
                    </div>


                    <table class="table">

                        <tr>

                            <td>id</td>

                            <td>Количество продуков</td>

                            <td>Сумма заказа</td>

                            <td>Дата заказа</td>

                        </tr>

                        @foreach ($order as $order)

                        <tr>

                            <td>{{ $order->id }}</td>

                            <td>{{ $order->amount }}</td>

                            <td>{{ $order->total }}</td>

                            <td>{{ $order->created_at }}</td>

                        </tr>

                        @endforeach

                    </table>

                </div>

            </div>

        </div>

    </div>

</div>

@endsection