routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/


// Product

Route::group([
    'prefix' => 'product',
    'as' => 'product.',
    'namespace' => 'Product',
    ], function () {

    Route::get('',                 ['as' => 'index',  'uses' => 'ProductController@index']);

    Route::get('create',           ['as' => 'create', 'uses' => 'ProductController@create']);


    Route::group([
        'prefix' => '{productId}',
        ], function () {

        Route::get('',             ['as' => 'show',  'uses' => 'ProductController@show']);

        Route::post('save',        ['as' => 'save',   'uses' => 'ProductController@save']);

        Route::get('edit',         ['as' => 'edit',   'uses' => 'ProductController@edit']);

        Route::any('update',       ['as' => 'update', 'uses' => 'ProductController@update']);

        Route::any('delete',       ['as' => 'delete', 'uses' => 'ProductController@delete']);


        // ProductImage

        Route::group([
            'prefix' => 'product__image',
            'as' => 'product__image.',
            ], function () {

            Route::get('',             ['as' => 'index',  'uses' => 'ProductImageController@index']);

            Route::get('create',       ['as' => 'create', 'uses' => 'ProductImageController@create']);
            
            Route::post('save',        ['as' => 'save',   'uses' => 'ProductImageController@save']);

            Route::get('edit/{id}',    ['as' => 'edit',   'uses' => 'ProductImageController@edit']);

            Route::any('update/{id}',  ['as' => 'update', 'uses' => 'ProductImageController@update']);

            Route::any('delete/{productImageId}',  ['as' => 'delete', 'uses' => 'ProductImageController@delete']);

        });

    });

});


// User

Route::group([
    'prefix' => 'user',
    'as' => 'user.',
    'namespace' => 'User',
    ], function () {

    Route::get('',         ['as' => 'index',  'uses' => 'UserController@index']);

    Route::get('edit/{id}',    ['as' => 'edit',   'uses' => 'UserController@edit']);
    Route::any('update/{id}',  ['as' => 'update', 'uses' => 'UserController@update']);

    Route::any('delete/{id}',  ['as' => 'delete', 'uses' => 'UserController@delete']);


    Route::group([
        'prefix' => 'cart',
        'as' => 'cart.'
        ], function () {

        Route::get('',          ['as' => 'index',
                                'uses' => 'UserProductController@index']);

        Route::get('create/{productId}',    ['as' => 'create',
                                'uses' => 'UserProductController@create']);

        Route::any('update/{userProductId}',['as' => 'update',
                                'uses' => 'UserProductController@update']);

        Route::any('delete/{userProductId}',  ['as' => 'delete',
                                   'uses' => 'UserProductController@delete']);

    });

});


// Order

Route::group([
    'prefix' => 'order',
    'as' => 'order.',
    'namespace' => 'Order',
    ], function () {

    Route::get('',             ['as' => 'index',  'uses' => 'OrderController@index']);

    Route::get('create',       ['as' => 'create', 'uses' => 'OrderController@create']);
    Route::post('save/{orderId}',        ['as' => 'save',   'uses' => 'OrderController@save']);

    Route::any('delete/{id}',  ['as' => 'delete', 'uses' => 'OrderController@delete']);


    Route::group([
        'prefix' => 'order__product',
        'as' => 'order__product.',
        'namespace' => 'Order',
        ], function () {

        Route::get('create',       ['as' => 'create', 'uses' => 'OrderProductController@create']);

        Route::any('delete/{id}',  ['as' => 'delete', 'uses' => 'OrderProductController@delete']);

    });
});


// Category

Route::group([
    'prefix' => 'category',
    'as' => 'category.',
    'namespace' => 'Category',
    ], function () {

    Route::get('',             ['as' => 'index',  'uses' => 'CategoryController@index']);

    Route::get('create',       ['as' => 'create', 'uses' => 'CategoryController@create']);
    Route::post('save',        ['as' => 'save',   'uses' => 'CategoryController@save']);

    Route::any('delete/{id}',  ['as' => 'delete', 'uses' => 'CategoryController@delete']);

});



// Home

Route::get('/', function(){
    return 'Laravel 5.3' . '<br><a href="/product">Продукты</a>';
});



    // Authentication Routes...
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout');

    // Registration Routes...
    Route::get('register', 'Auth\RegisterController@showRegistrationForm');
    Route::post('register', 'Auth\RegisterController@register');

    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');



    // Admin
    Route::get('admin', ['middleware' => 'admin', 'as' => 'admin', function() {

        return view('face.admin');

    }]);

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $table = 'user';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/User/UserController.php
<?php
namespace App\Http\Controllers\Admin\User;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Model\User\User;
use Illuminate\Http\Request;

class UserController extends Controller {

    public function index()
    {
        $user = User::orderBy('id', 'desc')->paginate(10);

        return view('admin.user.user.index', [
            'user' => $user
        ]);
    }

    public function create()
    {
        return view('admin.user.user.create');
    }

    public function save(Request $request)
    {
        $user = new User($request->all());

        $user->save();

        return redirect()->route('user.index');
    }

    public function edit($id)
    {
        $user = User::find($id);

        return view('admin.user.user.edit', [
            'user' => $user
        ]);
    }

    public function update(Request $request, $id)
    {
        $user = User::find($id);

        $user->update($request->all());

        return redirect()->route('user.index');
    }

    public function delete($id)
    {
        $user = User::where('id', '=', $id);
        $user->delete();

        return redirect()->back();
    }
}

app/Http/Controllers/Admin/User/UserProductController.php
<?php
namespace App\Http\Controllers\Admin\User;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Model\User\UserProduct;
use Illuminate\Http\Request;

class UserProductController extends Controller {

    public function index()
    {
        $userProduct = UserProduct::orderBy('id', 'desc')->paginate(10);

        return view('admin.user.user__product.index', [
            'userProduct' => $userProduct
        ]);
    }

    public function create()
    {
        return view('admin.user.user__product.create');
    }

    public function save(Request $request)
    {
        $userProduct = new UserProduct($request->all());

        $userProduct->save();

        return redirect()->route('userProduct.index');
    }

    public function edit($id)
    {
        $userProduct = UserProduct::find($id);

        return view('admin.user.user__product.edit', [
            'userProduct' => $userProduct
        ]);
    }

    public function update(Request $request, $id)
    {
        $userProduct = UserProduct::find($id);

        $userProduct->update($request->all());

        return redirect()->route('userProduct.index');
    }

    public function delete($id)
    {
        $userProduct = UserProduct::where('id', '=', $id);
        $userProduct->delete();

        return redirect()->back();
    }
}

app/Http/Controllers/User/UserController.php
<?php
namespace App\Http\Controllers\User;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Model\User\User;
use Illuminate\Http\Request;

class UserController extends Controller {

    public function index()
    {
        $user = User::find($id);

        return view('face.user.index', [
            'user' => $user
        ]);
    }

    public function create()
    {
        return view('admin.user.user.create');
    }

    public function save(Request $request)
    {
        $user = new User($request->all());

        $user->save();

        return redirect()->route('user.index');
    }

    public function edit(Request $request, $id)
    {
        $user = User::find($id);

        return view('face.user.index', [
            'user' => $user
        ]);
    }

    public function update(Request $request, $id)
    {
        $user = User::find($id);

        $user->update($request->all());

        return redirect()->back();
    }

    public function delete($id)
    {
        $user = User::where('id', '=', $id);
        $user->delete();

        return redirect('/product');
    }
}

app/Http/Controllers/User/UserProductController.php
<?php
namespace App\Http\Controllers\User;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Model\User\UserProduct;
use Illuminate\Http\Request;

class UserProductController extends Controller {

    public function index(Request $request)
    {
        $userProductList = UserProduct::where('user_id', '=', $request->user()->id)->get();


        return view('face.user.user__product.index', [
            'userProductList' => $userProductList
        ]);
    }

    public function create(Request $request, $productId)
    {
        $productCart = UserProduct::where('user_id', '=', $request->user()->id)->where('product_id', '=', $productId)->get();

        if ($productCart->count() > 0)
        {
            foreach ($productCart as $productCart)
            {
                $productCart->quantity = $productCart->quantity + 1;
                $productCart->save();     
            }

        } 

        else {

        $userProduct = new UserProduct();

        $userProduct->user_id = $request->user()->id;

        $userProduct->product_id = $productId;

        $userProduct->save();

        }

        return redirect()->back();
    }

    public function save(Request $request)
    {
        $userProduct = new UserProduct($request->all());

        $userProduct->save();

        return redirect()->route('userProduct.index');
    }

    public function edit($id)
    {
        $userProduct = UserProduct::find($id);

        return view('admin.user.user__product.edit', [
            'userProduct' => $userProduct
        ]);
    }

    public function update(Request $request, $userProductId)
    {
        $userProduct = UserProduct::find($userProductId);        
        $userProduct->quantity = $request->quantity;
        $userProduct->save();

        return redirect()->back();
    }

    public function delete($userProductId)
    {
        $userProduct = UserProduct::where('id', '=', $userProductId);
        $userProduct->delete();

        return redirect()->back();
    }
}

resources/views/face/user/create.blade.php
@extends('layouts.master')


@section('content')

<div class="container">

    <div class="row">

        <div class="col-md-8 col-md-offset-2">

            <div class="panel panel-default">

				<div class="panel-default">
					<div class="panel-heading">

						<h2 class="text">Добавить продукт</h2>


						<form action="{{ route('product.save', $productId) }}" method="POST" id="id-form_messages" >

						    <input type="hidden" name="_token" value="{{ csrf_token() }}">

						        <div class="form-group">
						            <label for="name">Название: </label>
						            <input class="form-control" placeholder="Пример: Samsung G55 mini" name="name" type="text" id="name">
						        </div>


						        <div class="form-group">
						            <input class="btn btn-primary" type="submit" value="Продолжить">
						        </div>

						</form>

					</div>

				</div>

            </div>

        </div>

    </div>

</div>

@endsection

resources/views/face/user/edit.blade.php
@extends('layouts.master')


@section('content')
<div class="container">

    <div class="row">

        <div class="col-md-8 col-md-offset-2">

            <div class="panel panel-default">

                <div class="panel-heading">

                    <h1 class="text-center">
                        id: {{ $id = $product->id }} / {{ $product->name }}
                    </h1>

                </div>

                <div class="panel-heading">
                    
                    <div class="panel panel-default">

                        <div class="panel-heading">

                            <h4 class="text">Отредактируйте товар</h4>

                                <hr/>

                                @include('face.product.__form.edit')

                        </div>

                    </div>

                    <hr>

                    @include('face.product__image.create')
                    
                    @include('face.product.list.image200x200')

                </div>

            </div>

        </div>

    </div>

</div>

@endsection

resources/views/face/user/index.blade.php
@extends('layouts.master')


@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">

				<div class="panel-heading">   
					<h2 class="text-center">Профиль</h2>
				</div>

				<div class="panel-heading">

					<div class="panel-heading">

					<label for="login">Логин: </label>
						{{ $user->name }}

						<hr>

					<label for="email">Email: </label>
						{{ $user->email }}

						<hr>

					<label for="created_at">Дата регистрации: </label>
						{{ $user->created_at }}
						
						<form action="{{ route('user.update', Request::route('id')) }}" method="get">

						    <input type="hidden" name="_token" value="{{ csrf_token() }}">

						    <hr>

							<label for="city">Город: </label>
							      <input type="text" name="city" value="{{ $user->city }}" />
							
							<hr>

							<label for="address">Адрес: </label>
							      <input type="text" name="address" value="{{ $user->address }}"/>

							<hr>
						
							<button class="btn btn-primary" type="submit">Обновить</button>

								<a class="btn btn-danger" href="{{ route('user.delete', Request::route('id')) }}">Удалить аккаунт</a>

						</form>

					</div>

				</div>


            </div>
        </div>
    </div>
</div>

@endsection